Code/ExpenseManager/src/main/java/com/amithfernando/web/mb/AbstractSecurityCheckMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.amithfernando.web.mb;

import com.amithfernando.web.util.JsfUtil;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.subject.Subject;

/**
 *
 * @author Amith Fernando
 */
public class AbstractSecurityCheckMB {

    protected Subject currentUser;

    protected void initSecurityCheck() {
        currentUser = SecurityUtils.getSubject();
    }

    public String getLoggedUserName() {
        return JsfUtil.getSessionAttrtibute("user").toString();
    }
}

Code/ExpenseManager/src/main/webapp/WEB-INF/template/components/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:panelGrid id="footer" styleClass="gradient" columns="2"  style="width: 100%; ">
        <h5>Copyright @ CBCIT Solutions </h5>
        <p:ajaxStatus style="float: right; width: 220px; height: 20px; " >  
            <f:facet name="start">  
                <h:graphicImage value="resources/images/ajax-loader.gif" />  
            </f:facet>  

            <f:facet name="complete">  
                <h:outputText value="" />  
            </f:facet>  
        </p:ajaxStatus>
    </h:panelGrid>

</html>

Code/ExpenseManager/src/main/webapp/WEB-INF/template/components/footerLogged.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:panelGrid id="footer" styleClass="gradient" columns="2"  style="width: 100%; ">
        <h5>Copyright @ CBCIT Solutions </h5>
        <p:ajaxStatus style="float: right; width: 220px; height: 20px; " >  
            <f:facet name="start">  
                <h:graphicImage value="../../resources/images/ajax-loader.gif" />  
            </f:facet>  

            <f:facet name="complete">  
                <h:outputText value="" />  
            </f:facet>  
        </p:ajaxStatus>
    </h:panelGrid>

</html>

Code/ExpenseManager/src/main/webapp/WEB-INF/template/components/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:panelGrid id="header" styleClass="gradient" columns="3" >
        <h:panelGrid id="nameContainer" columns="2" >
            <p:graphicImage id="logo" url="resources/images/hr_icon.jpg" />
            <h:panelGrid columns="1" >
               <h1 >Expense Management System</h1>
                <h4 >Version 1.0</h4>                
            </h:panelGrid>
        </h:panelGrid>
        <h:panelGrid columns="1" >
            <!-- EMPTY -->
        </h:panelGrid>
        <h:panelGrid id="userContainer" columns="2" >
            <!-- EMPTY -->
        </h:panelGrid>
    </h:panelGrid>

</html>

Code/ExpenseManager/src/main/webapp/WEB-INF/template/components/headerLogged.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <h:panelGrid id="header" styleClass="gradient" columns="3" >
        <h:panelGrid id="nameContainer" columns="2" >
            <p:graphicImage id="logo" url="../../resources/images/hr_icon.jpg" />
            <h:panelGrid columns="1" >
                <h1 >Expense Management System</h1>
                <h4 >Version 1.0</h4>              
            </h:panelGrid>
        </h:panelGrid>
        <h:panelGrid columns="1" >
            <!-- EMPTY -->
        </h:panelGrid>
        <h:panelGrid id="userContainer" columns="2" >
<!--            <p:graphicImage id="loggedUser" url="#{userLoginMB.userImage}" cache="false" />-->
            <h:panelGrid columns="1" >
                <h4>Hi #{loginMB.loggedUserName}</h4>
                <h:form id="frmLogout">
                    <p:splitButton value="Logout"   
                                   icon="ui-icon-disk"
                                   actionListener="#{loginMB.logout}">  
                        <p:menuitem value="Change Password" oncomplete="dlgPasswordChange.show()" update=":frmPasswordChange:pnlPasswordChange"/>
                        <p:separator />  
                        <p:menuitem value="About" oncomplete="dlgAbout.show()"/>  
                    </p:splitButton> 
                </h:form>
            </h:panelGrid>
        </h:panelGrid>
    </h:panelGrid>

</html>

Code/ExpenseManager/src/main/webapp/WEB-INF/template/components/navigation.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      >

    <h:form id="frmNavigation">
        <p:panelMenu style="width:190px"> 
            <p:submenu label="Dashboard" >  
                <p:menuitem value="Home"  action="adminDashboard?faces-redirect=true"
                            icon="ui-icon-home" rendered="#{navigationMB.isAdmin}"/>
                <p:menuitem value="Home"  action="dataentryDashboard?faces-redirect=true"
                            icon="ui-icon-home"  rendered="#{navigationMB.isDataEntry}"/>  

            </p:submenu> 
            <p:submenu label="User"  rendered="#{navigationMB.isAdmin}">
                <p:menuitem value="Manage"  action="user?faces-redirect=true"
                            icon="ui-icon-home" />  
                <p:menuitem value="Branch"  action="branch?faces-redirect=true"
                            icon="ui-icon-home" />  

            </p:submenu>

            <p:submenu label="Data"  rendered="#{navigationMB.isDataEntry}">
                <p:menuitem value="Expense Main Type"  action="expenseMainType?faces-redirect=true"
                            icon="ui-icon-home" />  
                <p:menuitem value="Expense Sub Type"  action="expenseSubType?faces-redirect=true"
                            icon="ui-icon-home" />  

            </p:submenu>


            <p:submenu label="Expense"  rendered="#{navigationMB.isDataEntry}">
                <p:menuitem value="Recurring Expense"  action="recurringExpense?faces-redirect=true"
                            icon="ui-icon-home" />  
                <p:menuitem value="Expense"  action="expense?faces-redirect=true"
                            icon="ui-icon-home" /> 
                <p:menuitem value="Expense Payment"  action="expensePayment?faces-redirect=true"
                            icon="ui-icon-home" /> 
                <p:menuitem value="Expense Refund"  action="expenseRefund?faces-redirect=true"
                            icon="ui-icon-home" /> 

            </p:submenu>

            <p:submenu label="Reports"  rendered="#{navigationMB.isDataEntry}">
                <p:menuitem value="Expense Summary"  action="expenseSummary?faces-redirect=true"
                            icon="ui-icon-home" />
                <p:menuitem value="Payment Summary"  action="paymentSummary?faces-redirect=true"
                            icon="ui-icon-home" />
            </p:submenu>

        </p:panelMenu>
        <p:spacer height="5" />
        <p:calendar mode="inline" />
    </h:form>

</html>